export const defaultData = {
  date: new Date().toISOString().substr(0, 10),
  airline: 'CX',
  fltno: '',
  prefix: 'B-',
  tail: '',
  acreg: '',
  type: 'Consumable',
  part: '',
  desc: '',
  serial: 'NIL',
  grn: '',
  qty: 0,
  store: 'BKK',
  usedBy: '',
  status: 'Pending',
  issued: { status: false, number: '', by: '' },
  returned: { status: false, number: '', by: '' },
  transferred: { status: false, number: '', by: '' },
};
