export const spareData = {
  date: new Date().toISOString().substr(0, 10),
  airline: 'CX',
  fltno: '',
  prefix: 'B-',
  tail: '',
  acreg: '',
  type: 'Consumable',
  part: '',
  desc: '',
  serial: 'NIL',
  grn: '',
  qty: 0,
  store: 'BKK',
  usedBy: '',
  status: 'Pending',
  issued: {
    by: '',
    date: null,
    number: '',
    status: false,
  },
  returned: {
    by: '',
    date: null,
    number: '',
    status: false,
  },
  transferred: {
    by: '',
    date: null,
    number: '',
    status: false,
  },
};
