export const defaultValues = {
  date: new Date().toISOString().substr(0, 10),
  airline: 'CX',
  fltno: '',
  prefix: 'B-',
  tail: '',
  acreg: '',
  ata: '',
  atd: '',
  bay: '',
  check1: '',
  check2: '',
  afac: 0,
  water: false,
  lavatory: false,
  extraGroundEquipments: [],
  tasks: [],
  chargeableServices: [],
  assignedDelays: [],
  remark: '',
  engineer: '',
  mechanic1: '',
  mechanic2: '',
  recordBy: '',
};
