import { currentDate } from '@/utils/currentDate';

export const defaultValues = {
  date: currentDate(),
  airline: 'CX',
  fltno: '',
  prefix: 'B-',
  tail: '',
  acreg: '',
  ata: '',
  atd: '',
  bay: '',
  check1: '',
  check2: '',
  check3: '',
  afac: 0,
  water: false,
  lavatory: false,
  extraGroundEquipments: [],
  tasks: [],
  chargeableServices: [],
  assignedDelays: [],
  remark: '',
  engineer: '',
  mechanic1: '',
  mechanic2: '',
  recordBy: '',
  isAcknowledged: false,
  acknowledgedBy: '',
  acknowledgedDate: '',
  hasCabinDefect: false,
  hasTechnicalDefect: false,
};
